# Site settings
title: EDDY's BLOG                     
SEOTitle: Here I Am! | EDDY        
header-img: img/post-bg-rwd.jpg   
email: eddyw2222@gmail.com    
description: "My name is Eddy Goei, study at WHU, major in CS."         
keyword: "EDDY, EDDY BLOG, 小葱的博客, xiaocong, 小葱, Microsoft, windows, WHU" 
url: "http://anlowee.github.io"          
baseurl: ""     

# Sidebar settings
sidebar: true                           
sidebar-about-description: "114514"  

# SNS settings
RSS: false
zhihu_username:     Sola
github_username:    anlowee
facebook_username:  eddyw2222
